# Generated by Django 5.2.9 on 2026-01-04 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_email', models.EmailField(max_length=254)),
                ('student_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=100)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('location', models.CharField(default='online', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_trial_course', models.BooleanField(default=False)),
                ('assigned_teacher_id', models.IntegerField(blank=True, null=True)),
                ('assigned_teacher', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('assigned', 'Assigné'), ('confirmed', 'Confirmé'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=255)),
                ('child_name', models.CharField(max_length=255)),
                ('child_age', models.IntegerField()),
                ('child_level', models.CharField(max_length=100)),
                ('subjects', models.JSONField()),
                ('availability', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parent_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=100)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('diplome', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('niveau_accepter', models.CharField(blank=True, max_length=255, null=True)),
                ('format_cours', models.CharField(blank=True, max_length=255, null=True)),
                ('matiere_niveau', models.CharField(blank=True, max_length=255, null=True)),
                ('subjects', models.JSONField()),
                ('availability', models.TextField(blank=True, null=True)),
                ('motivation', models.TextField()),
                ('cv_file', models.TextField()),
                ('cv_filename', models.CharField(max_length=255)),
                ('documents', models.JSONField(default=list)),
                ('accept_terms', models.BooleanField(default=False)),
                ('accept_verification', models.BooleanField(default=False)),
                ('accept_profile_sharing', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
