# Generated by Django 5.2.9 on 2026-01-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone Parent'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='assigned_teacher',
            field=models.CharField(blank=True, default='NULL', max_length=255, verbose_name='Nom Enseignant'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='assigned_teacher_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Enseignant'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Durée (heures)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_trial_course',
            field=models.BooleanField(default=False, verbose_name="Cours d'essai"),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='level',
            field=models.CharField(max_length=100, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.CharField(choices=[('online', 'En ligne'), ('home', 'À domicile')], default='online', max_length=20, verbose_name='Lieu du cours'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes supplémentaires'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='parent_email',
            field=models.EmailField(max_length=254, verbose_name='Email Parent'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='parent_id',
            field=models.CharField(max_length=100, verbose_name='ID Parent'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='parent_name',
            field=models.CharField(max_length=255, verbose_name='Nom Parent'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preferred_date',
            field=models.DateField(verbose_name='Date souhaitée'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preferred_time',
            field=models.TimeField(verbose_name='Heure souhaitée'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix/heure'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('assigned', 'Enseignant assigné'), ('confirmed', 'Confirmé'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student_name',
            field=models.CharField(max_length=255, verbose_name='Nom Élève'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Matière'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterModelTable(
            name='appointment',
            table=None,
        ),
    ]
