# Generated by Django 5.2.9 on 2026-02-22 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_appointment_options_appointment_parent_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentrequest',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='parentrequest',
            name='child_age',
        ),
        migrations.RemoveField(
            model_name='parentrequest',
            name='child_level',
        ),
        migrations.RemoveField(
            model_name='parentrequest',
            name='child_name',
        ),
        migrations.RemoveField(
            model_name='parentrequest',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='parentrequest',
            name='subjects',
        ),
        migrations.AddField(
            model_name='parentrequest',
            name='accept_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentrequest',
            name='children',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='parentrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parentrequest',
            name='parent_first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentrequest',
            name='parent_last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentrequest',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='parentrequest',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
