# Generated by Django 5.2.9 on 2026-02-27 20:31

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_parentrequest_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api.models.course_file_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('word', 'Word'), ('excel', 'Excel'), ('other', 'Autre')], default='other', max_length=10)),
                ('file_size', models.PositiveIntegerField(help_text='Taille en octets')),
                ('uploaded_by', models.CharField(choices=[('parent', 'Parent / Élève'), ('teacher', 'Enseignant')], max_length=10)),
                ('uploader_name', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_files', to='api.appointment')),
            ],
            options={
                'verbose_name': 'Fichier de cours',
                'verbose_name_plural': 'Fichiers de cours',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
